base_score: 0.5
booster: gbtree
callbacks: null
colsample_bylevel: 1
colsample_bynode: 1
colsample_bytree: 0
early_stopping_rounds: null
enable_categorical: false
eval_metric: null
features: '[''Delivery_person_Age'', ''Delivery_person_Ratings'', ''Distance'', ''Type_of_order_Buffet'',
  ''Type_of_order_Drinks'', ''Type_of_order_Meal'', ''Type_of_order_Snack'', ''Type_of_vehicle_electric_scooter'',
  ''Type_of_vehicle_motorcycle'', ''Type_of_vehicle_scooter'']'
gamma: 3.715125890776414
gpu_id: -1
grow_policy: depthwise
importance_type: null
interaction_constraints: ''
learning_rate: 0.300000012
max_bin: 256
max_cat_to_onehot: 4
max_delta_step: 0
max_depth: 6
max_leaves: 0
min_child_weight: 7
missing: .nan
model_class: XGBRegressor
monotone_constraints: ()
n_estimators: 180
n_jobs: 0
num_parallel_tree: 1
objective: reg:squarederror
predictor: auto
random_state: 0
reg_alpha: 40
reg_lambda: 1
sampling_method: uniform
scale_pos_weight: 1
subsample: 1
tree_method: exact
use_label_encoder: false
validate_parameters: 1
verbosity: null
